kind: environment
apiVersion: api.ibm.com/v1
metadata:
  name: Default_Environment
  version: "1.0"
  namespace: wM_Product_Petstore
  tags:
    - environment
spec:
  variables:
    - key: apikey
      isSecret: true
      value: dbdee0909b871dcb62145dcb72ce39ce
